config/routes.rb
Rails.application.routes.draw do
  resources :comments

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  #article
  resources :articles
  resources :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:edit,:update,:show, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    #to show plain text
    # render plain: params[:article].inspect
    @blog = Blog.new(blog_params)

    if @blog.save
      flash[:notice] = "Blog was successfully created!"
      redirect_to blog_path(@blog)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      flash[:notice] = "Article was successfully Updated!"
      redirect_to blog_path(@blog)
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    flash[:notice] = "Blog was successfully Deleted"
    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :description)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/views/blogs/_form.html.erb
<% if @blog.errors.any? %>
  <h2> The following errors:</h2>
  <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end%>

<%=form_for @blog do |f| %>
<p>
  <%= f.label :title %><br/>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :description %><br/>
  <%= f.text_area :description %>
</p>
  <p>
    <%= link_to "Back to Articles" , blogs_path %> |
    <%= f.submit %>
  </p>
<% end %>

app/views/blogs/edit.html.erb
<h1> Edit BLog</h1>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1> Showing All Blogs</h1>
<p>
  <%= link_to "Create New Blog", new_blog_path %>
</p>
<table>
  <tr>
    <th> Title</th>
    <th> Description</th>
    <th> Action</th>
  </tr>
  <% @blogs.each do |article| %>
    <tr>
      <td> <%= article.title %></td>
      <td> <%= article.description %></td>
      <td> <%= link_to "Show", blog_path(article) %></td>
      <td> <%= link_to "Edit", edit_blog_path(article) %> </td>
      <td> <%= link_to "Delete", blog_path(article),
                       method: :delete,
                       data: { confirm: "Are you Sure?"} %> </td>
    </tr>
  <% end %>
</table>

<%#= link_to :Delete , method: :delete, model: article_path %>

app/views/blogs/new.html.erb
<h1> Create new Blog</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1> Showing Selected Blog</h1>
<p>
  Title: <%= @blog.title %>
</p>
<p>
  Description: <%= @blog.description %>
</p>
<%= link_to "Back to Blogs" , blogs_path %> |
<%= link_to :Edit , edit_blog_path(@blog) %>
<%#= link_to :Delete , method: :delete, model: article_path %>