config/routes.rb
Rails.application.routes.draw do
  resources :comments

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  #article
  resources :articles
  resources :blogs
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

  def about
  end
end

app/views/welcome/about.html.erb
<h1>This is About page !!!!</h1>
<%= link_to('Home', welcome_home_path) %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <%#= image_tag("img2.jpeg", class: "rounded",width: "1000px", height: "500px") %>
  <%#= image_tag("img2.jpeg", class: "rounded mx-auto d-block",width: "1000px", height: "500px") %>
  <%#= image_tag("img2.jpeg", width: "1000px", height: "500px") %>
  <%= image_tag("modern_art.png", width: "1000px", height: "500px") %>
  <p>All way the up!!!!!!!!!!</p>
</div>

<!--<br>-->
<!--<%#= link_to('Home', root_path) %> |-->
<!--<%#= link_to('Articales', articles_path) %> |-->
<!--<%#= link_to('New Blog', blogs_path) %> |-->
<!--<%#= link_to('About', welcome_about_path) %> |-->
<!--<%#= link_to('Search', welcome_about_path) %> |-->
<!--app/assets/images/img2.jpeg-->

<%#= image_tag("img2.jpeg", width: "700px", height: "400px") %>