config/routes.rb
Rails.application.routes.draw do
  resources :comments

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  #article
  resources :articles
  resources :blogs
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="my url">My Test App</a>
      by <a href="/manishSingh"> Manish Singh</a>
    </small>
    <ul>
      <%= link_to "About", welcome_about_path %>
    </ul>

  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-8 col-xs-offset-2">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>


<%# flash.each do |name, msg| %>
<!--  <ul>-->
<!--    <li> <%#= msg %></li>-->
<!--  </ul>-->
<%# end %>

app/views/layouts/_navigation.html.erb
<!--<nav class="navbar navbar-expand-lg  bg-dark">-->
<nav class="navbar navbar-expand-lg bg-dark bg-gradient">
  <div class="container-fluid">
<!--    <a class="navbar-brand" id="logo" href="">Test-App</a>-->
    <%=link_to "Test App", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%=link_to "Blogs", blogs_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Actions
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Create New Article", new_article_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Create New Blog", new_blog_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "All Blogers", users_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
<!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
          <%=link_to "About US", welcome_about_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= "Admin" if current_user.admin?%> Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "View Your Profile ", user_path(current_user), class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "logout", logout_path, class: "dropdown-item", method: :delete %></li>
          </ul>
        </li>
      <%else %>
        <%= link_to "login", login_path, class: "btn btn-lg btn-secondary" %>
        <%= link_to "Sign up now", signup_path, class: "btn btn-lg btn-secondary"%>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render "layouts/navigation" %>
  <%= render "layouts/messages" %>
  <div class="container">
    <%= yield %>
    <br>
<!--    <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="Tooltip on top">-->
<!--      Tooltip on top-->
<!--    </button>-->
<!--    <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="left" title="Tooltip on left">-->
<!--      Tooltip on left-->
<!--    </button>-->
  </div>
  <%= render 'layouts/footer' %>
  <%#= params if Rails.env.development? %>


  </body>
</html>